#include "../GLCD/GLCD.h"
void decrementa_happiness();
void decrementa_satiety();
void incrementa_happiness();
void incrementa_satiety();
void animazione_happiness();
void animazione_satiety();
void animazione_costante();
void animazione_finevita();
void animazione_meal(int px, int py);
void animazione_snack(int px, int py);
void incrementa_tempo_vita();
void reset_alien();
void animazione_cuore();
void draw_alien_a(int px, int py);
void draw_alien_b(int px, int py);
void draw_selection_food(uint16_t t1, uint16_t s1, uint16_t t2, uint16_t s2);
int stato_alien_vivo();
void draw_speaker_stopped();
void draw_speaker_loud();
void stampa(int x,int y);